openapi: 3.0.0
info:
  title: Link Shearing
  description: API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
                email:
                  type: string
                backLink:
                  type: string
      responses:
        "201":
          description: user register successfully
  /verify:
    post:
      tags:
        - Auth
      requestBody:
        description: user verification request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                hash:
                  type: string
      responses:
        "200":
          description: user verified successfully
  /login:
    post:
      tags:
        - Auth
      requestBody:
        description: user login request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: user login successfully
  /users/all/{id}:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
      tags:
        - User
      requestBody:
        description: update avatar
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
      responses:
        "204":
          description: user updated
  /users/{id}:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
      tags:
        - User
      requestBody:
        description: user update request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
      responses:
        "204":
          description: user updated
