openapi: 3.0.0
info:
  title: Link Shearing
  description: API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
                email:
                  type: string
                backLink:
                  type: string
      responses:
        "201":
          description: user register successfully
